version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/var/lib/redis
    env_file:
      - .env
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
